'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.34014
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class iResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DX.iResources", GetType(iResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        '''  속성을 재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _Object() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Object", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _Property() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Property", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _Return() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Return", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _Select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property _STOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_STOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Append() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Append", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property approval() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("approval", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property arrow_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property arrow_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property arrow_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property arrow_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property ClearSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClearSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property column() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("column", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property columns() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("columns", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property compare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Confirm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Confirm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property connect_creating() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect_creating", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property database_connect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_connect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property database_disconnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_disconnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Excel_Export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel_Export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Excel_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Execute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Execute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property folder_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property folder_check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property folder_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property folder_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Group_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Group_Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Group_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Group_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property index() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property indexes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indexes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Initialize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Initialize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Mapping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mapping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property masking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("masking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Network_Connect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Network_Connect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Network_DisConnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Network_DisConnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Objects() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Objects", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property order() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("order", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property order_cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("order_cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property partition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("partition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property partitions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("partitions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Register() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Register", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property SAM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SAM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property schema() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("schema", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Sequence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sequence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Sequences() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sequences", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property SmartScript() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartScript", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property SQL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property SQL_Export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQL_Export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property SQL_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQL_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property tables() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tables", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property template() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("template", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Template_Export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Template_Export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Template_Import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Template_Import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property template_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("template_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property User_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property User_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
